apiVersion: v1
kind: Service
metadata:
  name: celery-svc
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    ms: celery-deployment

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: celery-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        ms: celery-deployment
    spec:
      containers:
      - name: celery-deployment
        image: alexeyebi/validaton
        ports:
        - containerPort: 5672