apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: celery-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        ms: celery-deployment
    spec:
      containers:
      - name: celery-deployment
        image: alexeyebi/validation
        ports:
        - containerPort: 80