apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: celery-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        ms: celery-deployment
    spec:
      containers:
      - name: celery-deployment
        image: alexeyebi/validation
        command: ['/bin/bash', 'run_celery.sh']
        volumeMounts:
          - name: data
            mountPath: /data
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: validation-pvc