apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: angular-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: angular-frontend
        tier: frontend  
    spec:
      containers:
        - name: angular-frontend
          image: eu.gcr.io/prj-ext-prod-faang-gcp-dr/dcc-portal-frontend/faang-frontend:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: angular-frontend-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: angular-frontend