apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: angular-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: angular-frontend
        tier: frontend  
    spec:
      containers:
        - name: angular-frontend
          image: eu.gcr.io/prj-ext-dev-faang-gcp-dr/dcc-portal-frontend/frontend-embassy-cloud:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: angular-frontend-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: angular-frontend