kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: protocols-storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: nfs-client