apiVersion: v1
kind: Service
metadata:
  name: daphne-svc
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    ms: daphne-deployment

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: daphne-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        ms: daphne-deployment
    spec:
      containers:
      - name: daphne-deployment
        image: alexeyebi/validation
        command: ['/bin/bash', 'run_daphne.sh']
        ports:
        - containerPort: 8000
        volumeMounts:
          - name: data
            mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: validation-pvc

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: validation-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  rules:
  - host:
    http:
      paths:
      - path: /validation(/|$)(.*)
        backend:
          serviceName: daphne-svc
          servicePort: 8000