apiVersion: v1
kind: Service
metadata:
  name: elixir-jsonschema-validator-svc
spec:
  ports:
  - port: 3020
    protocol: TCP
    targetPort: 3020
  selector:
    ms: elixir-jsonschema-validator-deployment

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elixir-jsonschema-validator-deployment
spec:
  selector:
    matchLabels:
      ms: elixir-jsonschema-validator-deployment
  replicas: 1
  template:
    metadata:
      labels:
        ms: elixir-jsonschema-validator-deployment
    spec:
      containers:
      - name: elixir-jsonschema-validator-deployment
        image: alexeyebi/elixir-jsonschema-validator
        ports:
        - containerPort: 3020