apiVersion: v1
kind: Service
metadata:
  name: elixir-jsonschema-validator-svc
spec:
  ports:
  - port: 3020
    protocol: TCP
    targetPort: 3020
  selector:
    ms: elixir-jsonschema-validator-deployment

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elixir-jsonschema-validator-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        ms: elixir-jsonschema-validator-deployment
    spec:
      containers:
      - name: elixir-jsonschema-validator-deployment
        image: quay.io/ebi-ait/biovalidator:1.0.0
        args: ["--server"]
        ports:
        - containerPort: 3020