apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    ms: redis-deployment

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        ms: redis-deployment
    spec:
      containers:
      - name: redis-deployment
        image: redis
        ports:
        - containerPort: 6379